#!/bin/sh

# if any of the commands fails in code, the entire script fails
set -o errexit
# exits if any of your variables is not set
set -o nounset

exec watchfiles --filter python celery.__main__.main --args '-A backend.taskapp worker -l INFO'
