#!/bin/sh

# if any of the commands fails in code, the entire script fails
set -o errexit
# fail exit if one of your pipe commands fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset


python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8080