version: "3.9"

services:
  django: &django # Using anchor(&) defining the alias of the service
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: food_app_drf_backend
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8080:8080"
    command: /start
    networks:
      core_backend_network:
        aliases:
          - food-app-django
      default:
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15-alpine
    volumes:
      - local_pg_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2

  celery-worker:
    <<: *django # Using asterisk(*) defining the usages of an alias
    image: food_app_drf_backend_celery_worker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celery-worker

volumes:
  local_pg_data: {}
  local_postgres_data_backups: {}

networks:
  core_backend_network:
    driver: bridge