# Generated by Django 4.2.7 on 2025-02-22 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique Code", max_length=120, unique=True
                    ),
                ),
                (
                    "cart_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Only Cart amount",
                        max_digits=10,
                        verbose_name="Cart Amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total amount",
                        max_digits=10,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "rebate_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Rebate amount",
                        max_digits=10,
                        verbose_name="Rebate Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("saved", "saved"),
                            ("approved", "approved"),
                            ("deleted", "deleted"),
                            ("rejected", "rejected"),
                        ],
                        default="saved",
                        help_text="Cart Status",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="The store",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_store",
                        to="store.store",
                        verbose_name="Store",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Cart User",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cart User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique Code", max_length=120, unique=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cart Item Quantity",
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Item Amount",
                        max_digits=10,
                        verbose_name="Item amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total Amount",
                        max_digits=10,
                        verbose_name="Total amount",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="Cart",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cartitem_cart",
                        to="cart.cart",
                        verbose_name="Cart",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Cart Item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cartitem_item",
                        to="item.item",
                        verbose_name="Cart Item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
