# Generated by Django 4.2.7 on 2024-03-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(
                help_text="Unique Code", max_length=120, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="code",
            field=models.CharField(
                help_text="Unique Code", max_length=120, unique=True
            ),
        ),
    ]
