# Generated by Django 4.2.7 on 2024-02-11 11:53

from django.db import migrations

import backend.user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", backend.user.models.CustomUserManager()),
            ],
        ),
    ]
