# Generated by Django 4.2.7 on 2024-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_remove_user_is_restaurant_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_visitor",
            field=models.BooleanField(default=True),
        ),
    ]
