# Generated by Django 4.2.7 on 2025-02-25 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_item_rating_brand_item_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.TextField(
                blank=True,
                help_text="set an image url",
                null=True,
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Type a SKU",
                max_length=20,
                null=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
