# Generated by Django 4.2.7 on 2024-04-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_item_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("daily food", "daily food"),
                    ("fast food", "fast food"),
                    ("meat", "meat"),
                    ("fish", "fish"),
                    ("beverage", "beverage"),
                    ("dessert", "dessert"),
                    ("kebab", "kebab"),
                    ("alcohol", "alcohol"),
                ],
                default="fast food",
                help_text="Select a Meal Type",
                verbose_name="Meal Type",
            ),
        ),
    ]
