# Generated by Django 4.2.7 on 2025-02-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="discount_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Set a discount rate",
                max_digits=5,
                verbose_name="Discount Rate",
            ),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
