# Generated by Django 4.2.7 on 2025-02-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        ("item", "0005_alter_item_discount_rate_alter_itemtype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="min_order_qty",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Set a Min order Qty",
                max_digits=5,
                verbose_name="Min Order Qty",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="store",
            field=models.ForeignKey(
                default=1,
                help_text="Select a Store",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store_items",
                to="store.store",
                verbose_name="Store",
            ),
        ),
    ]
