# Generated by Django 4.2.7 on 2025-02-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_alter_item_min_order_qty_alter_item_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Ex. 1Kg, 1Packet, 1Box, etc. (Kg, Packet, and, Box are unit",
                max_digits=4,
                verbose_name="Weight",
            ),
        ),
    ]
