# Generated by Django 4.2.7 on 2025-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0007_item_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="long_description",
            field=models.TextField(
                blank=True,
                help_text="Set a Long Description",
                null=True,
                verbose_name="Long Description",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Set a Short Description",
                max_length=300,
                null=True,
                verbose_name="Short Description",
            ),
        ),
    ]
