# Generated by Django 4.2.7 on 2025-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="city",
            field=models.CharField(default="dhaka", max_length=20, verbose_name="City"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactperson",
            name="country",
            field=models.CharField(
                default="bangladesh", max_length=20, verbose_name="Country"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactperson",
            name="postal_code",
            field=models.CharField(
                default="8240", max_length=10, verbose_name="Postal Code"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactperson",
            name="state",
            field=models.CharField(
                default="dhaka", max_length=50, verbose_name="State"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="address",
            field=models.CharField(
                default="vejlby toften",
                max_length=120,
                verbose_name="Contact Person address",
            ),
            preserve_default=False,
        ),
    ]
