# Generated by Django 4.2.7 on 2024-02-19 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="address",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=120,
                null=True,
                verbose_name="Contact Person address",
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="contact",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_person_contact",
                to="contact.contact",
                verbose_name="Contact Person",
            ),
        ),
    ]
