# Generated by Django 4.2.7 on 2025-04-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactperson_city_contactperson_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="mobile number"
            ),
        ),
    ]
