# Generated by Django 4.2.7 on 2024-02-20 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_contact_code_alter_contactperson_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="contact",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_person_contact",
                to="contact.contact",
                verbose_name="Contact Person",
            ),
        ),
    ]
