# Generated by Django 4.2.7 on 2024-02-20 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_alter_contactperson_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="contact",
            field=models.ForeignKey(
                help_text="Contact for person",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_person_contact",
                to="contact.contact",
                verbose_name="Contact",
            ),
        ),
    ]
