# Generated by Django 4.2.7 on 2024-02-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_contactperson_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactperson",
            name="is_visitor",
        ),
    ]
