# Generated by Django 4.2.7 on 2024-02-26 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact", "0006_remove_contactperson_is_visitor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="user",
            field=models.OneToOneField(
                help_text="Contact person user",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_person_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
