# Generated by Django 4.2.7 on 2024-03-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0008_contactgroup_alter_contact_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroup",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Contact Group Name",
                max_length=25,
                verbose_name="Name",
            ),
        ),
    ]
