# Generated by Django 4.2.7 on 2025-02-22 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique Code", max_length=120, unique=True
                    ),
                ),
                (
                    "order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Only Order amount",
                        max_digits=10,
                        verbose_name="Order Amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total amount",
                        max_digits=10,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "rebate_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Rebate amount",
                        max_digits=10,
                        verbose_name="Rebate Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("released", "released"),
                            ("on shipping", "on shipping"),
                            ("paid", "paid"),
                            ("cancelled", "cancelled"),
                            ("in progress", "in progress"),
                        ],
                        default="pending",
                        help_text="Order Status",
                        verbose_name="status",
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("cash on delivery", "cash on delivery"),
                            ("card", "card"),
                            ("paid via mobile", "paid via mobile"),
                        ],
                        default="cash on delivery",
                        help_text="Paid By",
                        verbose_name="Paid By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="The Store",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_store",
                        to="store.store",
                        verbose_name="Store",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Order User",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Order User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique Code", max_length=120, unique=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Order Item Quantity",
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Item Amount",
                        max_digits=10,
                        verbose_name="Item amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total Amount",
                        max_digits=10,
                        verbose_name="Total amount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Order Item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orderitem_item",
                        to="item.item",
                        verbose_name="Order Item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orderitem_order",
                        to="order.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
