# Generated by Django 4.2.7 on 2024-03-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_item_code"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(
                help_text="Unique Code", max_length=120, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="code",
            field=models.CharField(
                help_text="Unique Code", max_length=120, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                help_text="Order Item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orderitem_item",
                to="item.item",
                verbose_name="Order Item",
            ),
        ),
    ]
