# Generated by Django 4.2.7 on 2024-02-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_alter_restaurant_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="code",
            field=models.CharField(help_text="Unique Code", max_length=120),
        ),
    ]
