# Generated by Django 4.2.7 on 2024-02-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_restaurant_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="closing_time",
            field=models.TimeField(
                help_text="Closing time", verbose_name="Closing time"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_time",
            field=models.TimeField(
                help_text="Opening time", verbose_name="Opening time"
            ),
        ),
    ]
