# Generated by Django 4.2.7 on 2024-03-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_restaurant_closing_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="code",
            field=models.CharField(
                help_text="Unique Code", max_length=120, unique=True
            ),
        ),
    ]
