apiVersion: v1
kind: Service
metadata:
  name: food-app-ws
spec:
  selector:
    app: food-app-ws
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30037