apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
data:
  POSTGRES_HOST: 'postgres.default'
  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'food_backend'
  POSTGRES_USER: 'tAImfqUsWArtfTwnqCcYHRvzkmsABREbBFVW'
  POSTGRES_PASSWORD: 'KHz6tof50AWJlMa8qyeaaSEc7ydfdEEWcnCmJsaWmHUi7HjXG7YIl9OYk6JIy8BK0eklQE'
  DJANGO_ALLOWED_HOSTS: '*'
  DJANGO_SETTINGS_MODULE: 'config.settings.staging'
  SECRET_KEY: 'tz#@421=7&)^m)xxzmsq&id6c5yheb+qc4*ezn3+k0gqek4u%b'
  DEBUG: 'True'
  ACCESS_TOKEN_LIFETIME: '1800'
  REFRESH_TOKEN_LIFETIME: '86400'
  REDIS_URL: 'redis://redis:6379/0'
  CELERY_TASK_TIME_LIMIT: '400'
  CELERY_TASK_SOFT_TIME_LIMIT: '60'
  DEFAULT_FROM_EMAIL: 'risenboy24@gmail.com'
  EMAIL_HOST: 'smtp.gmail.com'
  EMAIL_PORT: '587'
  EMAIL_HOST_USER: 'risenboy24@gmail.com'
  EMAIL_HOST_PASSWORD: 'tite fcqn ztid wiwx'
  EMAIL_USE_TLS: 'True'
  DJANGO_EMAIL_BACKEND: 'django.core.mail.backends.console.EmailBackend'
  GUNICORN_TIMEOUT: '30'
  GUNICORN_NUM_WORKERS: '3'
  DATABASE_URL: "postgres://tAImfqUsWArtfTwnqCcYHRvzkmsABREbBFVW:KHz6tof50AWJlMa8qyeaaSEc7ydfdEEWcnCmJsaWmHUi7HjXG7YIl9OYk6JIy8BK0eklQE@postgres:5432/food_backend"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CHANNEL_LAYERS: "redis://redis:6379/0"
  STATIC_ROOT: "/data/staticfiles"
  CSRF_TRUSTED_ORIGINS: 'http://0.0.0.0,http://127.0.0.0:8080,http://localhost:8080,http://192.168.49.2:30036,http://192.168.49.2:30040'